site_name: Appunti Elettronica Applicata 2024
theme:
  name: material
  palette:
    scheme: slate
    primary: black
  features:
    - navigation.expand
markdown_extensions:
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.arithmatex:
      generic: true
  
nav:
  - index.md
  - Lezioni:
    - lezioni/lezione_01.md

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

plugins:
  - search:
      lang: it
  