site_name: Appunti Elettronica Applicata 2024
theme:
  name: material
  palette:
    scheme: slate
    primary: black
  features:
    - navigation.expand
    - content.tooltips
markdown_extensions:
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.caret
  - footnotes 
  - abbr
  - attr_list
  - pymdownx.snippets:
      auto_append:
        - includes/abbreviations.md
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.details
  - pymdownx.superfences
watch:
  - includes
  
nav:
  - index.md
  - Lezioni:
    - Teoria:
      - lezioni/lezione_01.md
      - lezioni/lezione_02.md
      - lezioni/lezione_03.md
      - lezioni/lezione_04.md
      - lezioni/lezione_05.md
      - lezioni/lezione_06.md
      - lezioni/lezione_07.md
      - lezioni/lezione_08.md
      - lezioni/lezione_09.md
      - lezioni/lezione_10.md
      - lezioni/lezione_11.md
      - lezioni/lezione_12.md
      - lezioni/lezione_13.md
    - Verilog:
      - lezioni/verilog.md
extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

plugins:
  - search:
      lang: it